Video-admin + Update Pendulum
e-lab-FREE/FREE_Web pull request #13
Opened 2022-04-19 15:26 UTC by PedroRossa98

Adding the video stream configuration page and closing the pendulum experiment page

2022-04-21 08:18 UTC, airguru requested changes
@PedroRossa98 Can we please bring back the monte carlo experiment config into db? I have almost no means to test anything....

2022-04-21 08:18 UTC, airguru commented on free/templatetags/free_extras.py
> +from django.conf import settings
This would be better to do using django custom context processors. I will adjust that.

2022-04-21 08:18 UTC, airguru commented on free/views/api.py
> +        if not self.instance.status in ['C','N','F']:
@PedroRossa98 should we add the new endpoint in this PR or in another iteration?

2022-04-21 08:18 UTC, airguru commented on freeweb/settings.py
> +JANUS_SERVER_ADDRESSS="http://localhost:8088/janus"
I will move all of this into .env

2022-04-21 08:18 UTC, airguru commented on free/videoConfig/templates/videoConfig.html
> +{% extends 'free/base.html' %}
This crashes the app for me (as I don't have video configured). We need to load the page and display some error there. 

I will try the admin integration as well...

2022-04-21 08:19 UTC, airguru commented on free/templates/free/experiment.html
> -                    {% block tabheaders %}
@joao-n-silva We can pre-fill the three tabs for each experiment, but still leave optional additions for experiment creator?

2022-04-21 11:21 UTC, PedroRossa98 commented on free/templates/free/experiments/pendulum_old.html
> +        server = "http://elab1.ist.utl.pt:8088/janus"
We are no longer using this file lets delete it

2022-04-21 11:24 UTC, PedroRossa98 commented
I will comit the montecarlo so you can test the pages

2022-04-21 16:19 UTC, airguru commented
TODO:

- [ ] Make videoConfig page not display an 500 error when no janus is configured
- [ ] Access the experiment page without creating an execution
- [ ] Make experiment js cope with empty execution json
- [ ] Bring back the MC

2022-04-25 20:56 UTC, airguru commented
Access the experiment page without creating an execution - completed.

2022-05-12 14:34 UTC, airguru approved these changes

2022-05-13 14:57 UTC, merged